name: swap_it
description: Erichthonius 2022 Flutter Hackathon entry

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  flutter_bloc: 7.0.1
  colorize_lumberdash: 3.0.0
  google_fonts: 2.2.0
  flutter_svg: 1.0.3
  flutter_switch: 0.3.2
  image: 3.1.3
  confetti: 0.6.0
  image_picker: 0.8.4+11
  extended_image: 5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_generator: 0.1.0+0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/swap_it_logo.svg
    - assets/images/swap_it_alternative_logo.svg
    - assets/images/easy_map.svg
    - assets/images/medium_map.svg
    - assets/images/hard_map.svg
    - assets/images/easy_map_preview.svg
    - assets/images/medium_map_preview.svg
    - assets/images/hard_map_preview.svg

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
